name: Automated LORIS to ReproSchema Update

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
    inputs:
      data_dictionary_file:
        description: "Path to data dictionary file to use"
        required: false
        default: ""
      manual_trigger:
        description: "Manual trigger for update"
        required: false
        default: "true"

jobs:
  update:
    uses: ./.github/workflows/reusable-update.yml
    secrets: inherit
    with:
      data_dictionary_file: ${{ github.event.inputs.data_dictionary_file }}
